import { type NextPage } from "next";
import Head from "next/head";

const SinglePostPage: NextPage = () => {
  // if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        {/* the code below makes the content full, unless its medium or large
        in which case it is 2xl max */}
        <div>POST VIEW</div>
      </main>
    </>
  );
};

export default SinglePostPage;
